<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX58ViR8\Mikedevs_HelpersBundle_KernelTestingDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX58ViR8/Mikedevs_HelpersBundle_KernelTestingDebugContainer.php') {
    touch(__DIR__.'/ContainerX58ViR8.legacy');

    return;
}

if (!\class_exists(Mikedevs_HelpersBundle_KernelTestingDebugContainer::class, false)) {
    \class_alias(\ContainerX58ViR8\Mikedevs_HelpersBundle_KernelTestingDebugContainer::class, Mikedevs_HelpersBundle_KernelTestingDebugContainer::class, false);
}

return new \ContainerX58ViR8\Mikedevs_HelpersBundle_KernelTestingDebugContainer([
    'container.build_hash' => 'X58ViR8',
    'container.build_id' => 'f6e41b55',
    'container.build_time' => 1617181219,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX58ViR8');
