<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXzJaYBJ\Mikedevs_HelpersBundle_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXzJaYBJ/Mikedevs_HelpersBundle_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXzJaYBJ.legacy');

    return;
}

if (!\class_exists(Mikedevs_HelpersBundle_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXzJaYBJ\Mikedevs_HelpersBundle_KernelTestDebugContainer::class, Mikedevs_HelpersBundle_KernelTestDebugContainer::class, false);
}

return new \ContainerXzJaYBJ\Mikedevs_HelpersBundle_KernelTestDebugContainer([
    'container.build_hash' => 'XzJaYBJ',
    'container.build_id' => '08d02a1b',
    'container.build_time' => 1617287034,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXzJaYBJ');
