<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVZ1TwX2\Mikedevs_HelpersBundle_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVZ1TwX2/Mikedevs_HelpersBundle_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerVZ1TwX2.legacy');

    return;
}

if (!\class_exists(Mikedevs_HelpersBundle_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerVZ1TwX2\Mikedevs_HelpersBundle_KernelTestDebugContainer::class, Mikedevs_HelpersBundle_KernelTestDebugContainer::class, false);
}

return new \ContainerVZ1TwX2\Mikedevs_HelpersBundle_KernelTestDebugContainer([
    'container.build_hash' => 'VZ1TwX2',
    'container.build_id' => '04ac8965',
    'container.build_time' => 1617183501,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVZ1TwX2');
