<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container04HKvlt\Mikedevs_HelpersBundle_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container04HKvlt/Mikedevs_HelpersBundle_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container04HKvlt.legacy');

    return;
}

if (!\class_exists(Mikedevs_HelpersBundle_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container04HKvlt\Mikedevs_HelpersBundle_KernelDevDebugContainer::class, Mikedevs_HelpersBundle_KernelDevDebugContainer::class, false);
}

return new \Container04HKvlt\Mikedevs_HelpersBundle_KernelDevDebugContainer([
    'container.build_hash' => '04HKvlt',
    'container.build_id' => 'd89bec37',
    'container.build_time' => 1617183536,
], __DIR__.\DIRECTORY_SEPARATOR.'Container04HKvlt');
